src/model/Geo.js, src/model/LocationApi.js, src/utils.js, test/unit/model/Geo.js, test/unit/utils.js
This is based on code from the ThrowAway server.
Taking into account comments that the function should be in the Geo module.
=> Implement getClosestPlatPoint

src/comm/Session.js
Fixes trello#56 https://trello.com/c/9eKTLjhG
=> Allow ping messages during login

deploy/eleven-server.service, deploy/eleven-server.service.VAGRANT, package.json, src/data/RequestContext.js
Two seemingly innocuous changes that drastically improve the GS memory
usage behavior (see commit messages for details).
=> fixes for memory issues

src/comm/Session.js, src/model/Player.js, test/unit/comm/Session.js
Fixes trello#54 https://trello.com/c/bxKicCMS
=> fix worker crash when sending CLOSE message to offline player

.jscsrc, src/data/objrefProxy.js, src/data/pers.js, src/model/Location.js, test/func/data/pers.js, test/func/model/Location.js, test/unit/data/objrefProxy.js, test/unit/data/pers.js
another attempt to fix trello#41 https://trello.com/c/sFSHvH2a
=> actually wrap game objects in proxy wrapper

src/model/GameObject.js, test/func/model/Bag.js, test/func/model/GameObject.js, test/func/model/Quest.js
Fixes trello#57 https://trello.com/c/TLesSdRt
=> allow overriding prototype properties with changed values

src/comm/replServer.js
The default way of rendering results in the REPL (util.inspect) may
require resolving objrefs (and have further side effects), which only
works within a request context, so move this from the REPL callback
into the evaluated function.
=> generate REPL return value within the request context

src/model/Item.js, src/model/ItemApi.js, src/model/ItemMovement.js, test/unit/model/ItemMovement.js
Address  Trello#29 https://trello.com/c/hQnlj8Jj/29-npc-movement
I expect this large of a merge will require some cleaning up and comments.
But I need to get the process started.
=> Enable NPC Movement

src/model/Item.js, src/model/ItemApi.js, src/model/ItemMovement.js, test/func/model/ItemMovement.js, test/unit/model/ItemMovement.js
First pass; pathfinding across platforms only covers the most basic
case, not all features are implemented, and there will certainly be
bugs, especially in less common situations.
This is a revised version of #75.
=> NPC movement

src/config.js, src/model/Location.js, src/server.js
* make location unload interval configurable and optional
* add explicitly scheduled periodic GC as a debugging option
=> make location unloading optional

src/model/ItemApi.js, src/model/ItemMovement.js
Also general chicken movement improvements
=> Resend Fix Trello#74, chickens not landing properly.

src/model/Item.js, src/model/ItemApi.js, src/model/Location.js, test/unit/model/Item.js, test/unit/model/Location.js
Revised version of #105.
Fixes trello#66.
=> implement Item.apiFindCloseItem

src/data/pers.js, src/model/GameObject.js, src/model/Item.js, src/model/Location.js, test/func/data/pers.js, test/unit/data/pers.js
See https://trello.com/c/Z7pe7X0g for a description of the issue,
and the commit messages for details about the workaround.
=> prevent loading multiple instances of the same game object

src/model/GameObject.js, test/func/data/pers.js, test/func/model/GameObject.js, test/unit/model/GameObject.js
* replace setInterval with setTimeout (see commit messages for details)
* NB: this change modifies game object data structure and therefore
requires fixing up or resetting game data
=> intervals to timers

src/comm/replServer.js, src/logging.js
add logging/log module to REPL context, so the log level for each
stream can be changed at runtime
=> allow changing log level at runtime via REPL

src/comm/Session.js, src/config.js, src/data/objrefProxy.js, src/data/rpc.js, src/data/rpcApi.js, src/metrics.js, src/server.js, tools/bench.js
Various small changes and fixes (typos, log messages, added
metrics etc.); see commit log messages for details.
=> Miscellaneous minor fixes and adjustments

src/comm/Session.js
Directly sending out any message sent by GSJS code causes client-side
errors during the (re)login process (see https://trello.com/c/FhXrtwJ5);
just dropping them causes other problems (https://trello.com/c/UFPduR2B).
Therefore, let's try queueing them up and sending them out at once, in
FIFO order, after the (re)login has finished.
=> queue messages during login and send them afterwards

.travis.yml, src/data/pers.js
=> Integrate Travis

src/comm/Session.js, src/comm/sessionMgr.js, src/data/RequestQueue.js, src/data/pers.js, src/data/rpcApi.js, src/model/GameObject.js, src/server.js, test/unit/data/RequestQueue.js
Several bugfixes and workarounds (for issues introduced by v0.2.0) to improve overall server stability.
=> v0.2 resilience fixes

.gitattributes, package.json, src/data/RequestQueue.js, src/data/pers.js, src/data/rpc.js, src/model/Bag.js, src/model/DataContainer.js, src/model/GameObject.js, src/model/Geo.js, src/model/Group.js, src/model/Item.js, src/model/Location.js, src/model/LocationApi.js, src/model/globalApi.js, test/func/model/Item.js, test/func/model/Location.js, test/unit/model/GameObject.js
See commit messages for details.
This partially supersedes #151.
=> Support for instanced locations

src/data/rpc.js, src/model/DataContainer.js
see https://trello.com/c/iQB6EmQc
=> Prevent uncaught error in RPC handler

src/comm/replServer.js
see https://trello.com/c/ENo0yNCK
=> Handle networking problems in REPL server gracefully

src/comm/slackChat.js, test/unit/comm/slackChat.js
see https://trello.com/c/QmtCC6gr
=> Handle missing user for incoming Slack message

src/comm/replServer.js, src/data/pers.js, src/data/rpcApi.js, src/logging.js, src/model/Bag.js, src/model/Item.js, src/model/Player.js, src/model/globalApi.js
See https://trello.com/c/A9JUHeed
=> Don't restart item movement when not in a location

src/model/Item.js
See https://trello.com/c/3FTXOPD4
=> Actually let cubimals go when they are set free

src/utils.js
See https://trello.com/c/af9IilPi
=> Find correct item placement platform on furniture

src/data/pers.js, src/model/Bag.js, src/model/Item.js, src/model/gsjsBridge.js
See https://trello.com/c/5mrOUY40
=> Don't unload the the firefly jar mid-whistle

src/data/rpc.js, src/model/Location.js
See https://trello.com/c/imsxHSAI
=> Allow copying placeholder location for quests

src/comm/Session.js, src/model/GameObject.js
See https://trello.com/c/mZ9fW49e
=> Reduce log error spam

src/data/RequestContext.js, src/data/RequestQueue.js, src/model/Player.js, src/model/globalApi.js
See https://trello.com/c/Cf5xI3b0
=> Prevent group chat disconnects

src/data/pers.js, src/model/Location.js, src/model/Player.js, test/func/model/Location.js
see https://trello.com/c/KQElr08c
=> Clear stale location instance group references

src/model/Location.js
see https://trello.com/c/0udEozF3
=> Don't unload locations where something is growing

deploy/deploy.sh, deploy/eleven-server.service, deploy/eleven-server.service.VAGRANT, src/data/pers.js, src/model/Geo.js, src/model/Item.js, src/model/Location.js, test/func/data/pers.js, test/func/model/Location.js
* properly clean up location instance group refs (fix for bd5334c)
* clean up refs in certain items
=> Stale object reference cleanup

src/model/globalApi.js
Fixes https://trello.com/c/CBloixMa
=> Simplify game object cloning

config_local.js.SAMPLE_PROD, src/data/rpcApi.js
See https://trello.com/c/UsCDrDlE
=> Limit the number of concurrent sessions per GS worker

src/data/rpc.js, test/func/data/rpc.js
See https://trello.com/c/46iI5RUo
=> Handle RPCs on nonexistent game objects gracefully

src/model/Geo.js, test/unit/model/Geo.js
See https://trello.com/c/fGHRvCBj
=> Prevent accidental modification of loc template geometry

src/model/Player.js
See https://trello.com/c/qjHIzAgi
=> Make sure announcements are sent during an inter-GS move

bench/suites/amf.js, config_base.js, npm-shrinkwrap.json, package.json, src/comm/Session.js, test/setup.js
See https://trello.com/c/wEhfAddz
=> Add a config setting for choosing an AMF library

.jshintrc, npm-shrinkwrap.json, package.json, src/comm/Session.js, src/data/pers.js, src/model/Geo.js, src/model/ItemMovement.js, test/func/model/ItemMovement.js, test/unit/data/pers.js, test/unit/model/Geo.js
See https://trello.com/c/teexKtat
=> More defensive NPC movement error handling

src/comm/slackChat.js
* If a Slack message came from the connected Slack integration (itself), ignore it.
=> Do not echo self on a slack message

src/comm/policyServer.js
* Errors from the policy server need to be handled, even if we don't really care about them.
Fixes https://trello.com/c/XwUOgL8y
=> Handle errors on the policy server
