src/config.js
src/logging.js
src/model/globalApi.js
test/unit/config.js
test/unit/logging.js

* write game events logged via global API function apiLogAction to a
dedicated log file
* combine logs for all worker processes into shared log files (easier
to read/handle, and no real downside as long as log rotation is done
with an external tool, e.g. logrotate)

log apiLogAction calls to separate logfile

---

src/model/Location.js
src/model/Player.js
test/func/model/Location.js

release locations with no active players from the live object cache, to
conserve memory and keep GC times manageable

unload inactive locations

---

src/data/pers.js
src/model/GameObject.js
test/unit/model/GameObject.js

When loading game objects from persistence, immediately execute
timer calls that should have happened in the past, and call interval
functions as many times as they would have been called if the object
had been "live" the whole time.

catch up on missed timer/interval calls when loading objects

---

src/data/RequestContext.js
src/model/GameObject.js
test/func/model/GameObject.js
test/unit/data/RequestContext.js

Mark objects with a 'stale' flag when unloading them, so
timer/interval calls can detect when they are firing on an already
unloaded object and abort the call.

prevent timers on unloaded objects from firing

---

src/model/Item.js
test/func/model/Bag.js
test/func/model/Item.js
test/func/model/Location.js
test/unit/model/Item.js

Fail immediately when something is trying to set NaN as an item's x or y
coordinate (otherwise RethinkDB just fails writing the values later on)

prevent setting NaN as item coordinates

---

src/model/Player.js

This error recovery feature makes GS behavior in other situations worse,
see e.g. https://trello.com/c/LyoLOUID so remove it for the time being.
Calling `onDisconnect` after a basically arbitrary delay (100ms), with
no further questions asked, seems like a bad idea anyway; it might be
better to handle the general issue ("old" player instances stuck in
locations after errors) from the location side.

remove the "offline player removal" hack

---

src/data/rpcApi.js

Calling adminBackfillNewxpPhysics will give players the basic physics upgrades on a reset or on creation (plus the physics upgrade cards don't show up in the card pool).

Give players physics upgrades on reset/creation

---

src/model/Player.js
test/func/comm/Session.js
test/func/model/Bag.js
test/func/model/Item.js
test/func/model/Location.js
test/func/model/Player.js
test/helpers.js
test/unit/model/Location.js

when a Player object has no session associated (no connected client,
e.g. due to an unclean disconnect), changes and announcements are
never processed/sent, so don't queue them in the first place

don't queue changes&announcements for offline players

---

src/comm/Session.js
test/unit/comm/Session.js

Handle ping messages in the game server (as opposed to deferring to
GSJS), since this seems more in line with original server behavior
(client ignores changes/announcements in ping replies, ping messages
interrupting meditation, etc)

handle ping messages directly in GS

---

src/model/Bag.js
src/utils.js
test/unit/model/Bag.js
test/unit/utils.js

In some situations, GSJS code supplies a string-type slot argument to
inventory handling functions, which caused those functions to fail
silently and cause odd effects.
Fixes trello#85.

parse slot number argument if necessary

---

.jshintrc
src/data/RequestContext.js
src/data/pers.js
test/func/model/Location.js
test/mock/pers.js
test/unit/data/RequestContext.js
test/unit/data/pers.js

Make sure post-request persistence operations are performed in a way that
prevents invalid object references (first add new objects, then modify
existing ones, then remove deleted).

perform persistence operations in safe order

---

src/model/GameObjectApi.js

`apiSetInterval` needs to specify the `interval` option, otherwise it
just creates a one-off timer (this caused newly created trants not to
grow/decay).

actually start interval in apiSetInterval

---

src/data/rpc.js
src/data/rpcApi.js

Prevent sending RPC requests back and forth indefinitely between
GS worker processes in split-brain/inconsistent state situations.
Fixes trello#108 https://trello.com/c/nRBXdPGn

prevent RPC forwarding cycles

---

src/model/Geo.js
test/unit/fixtures/GLI32G3NUTD100I.json

In some cases (e.g. doors with `connections`), GSJS modifies the connect
without adjusting the target accordingly. Make sure the geometry is still
saved correctly under these circumstances.
see https://trello.com/c/zz3sAeM4

fix door connects not being serialized correctly

---

test/func/comm/Session.js
test/func/data/rpcApi.js
test/func/model/ItemMovement.js
test/func/model/gsjsBridge.js

Make some timing sensitive tests more generous, and increase some timeouts, to make tests fail less often on machines under load (such as the one currently running our build environment).

More liberal test timeouts

---

src/data/RequestQueue.js
src/data/rpc.js
src/model/GameObject.js
src/model/Item.js
src/model/ItemMovement.js
test/func/model/ItemMovement.js
test/unit/model/GameObject.js

* stop NPC movement asynchronously to prevent infinite recursion
(see comment on https://trello.com/c/LnqVJcXV)
* cancel timer calls that are already in a request queue
(see https://trello.com/c/KeHx7Fdb)
* prevent infinite RPC cycles

NPC movement related bugfixes

---

src/model/Location.js

* Instead of keeping players from being able to play or enter a location due to persisted bad references, delete them when calling `gsOnLoad`
(This does not fix the underlying issue, but allows players to continue playing the game)

Remove broken refs from locations items in gsOnLoad

---

src/comm/slackChat.js
src/data/RequestQueue.js
src/data/rpc.js

* If two servers RPC eachother at the same time, it may lead to a race if the requests are pushed to RQs that are waiting for RPC responses. To avoid this, mark the RQ as waiting for an RPC response, and check for this when pushing to it.
fixes https://trello.com/c/glgN2tVw and probably any other instances of "RPC Timed out" errors.

Avoid RPC races

---

src/data/pers.js

* If a server creates a new GO, and it is accessed in the same request by another server, just fetch a serialised copy so we have something to work with.
fixes https://trello.com/c/iWFIJYO5

Fetch new unpersisted GOs through RPC

---

src/model/IdObjRefMap.js

* null values here could be happening due to the use of delete over splice on an array, but lets fix the
issue here as we can safely ignore nulls (and anything else that isn't an object).

Ignore null values in IdObjRefMap constructor
